# Praxis — developer command runner.
# Usage: `just <recipe>`. Run `just` with no arguments to list recipes.
# Requires: docker, uv (backend), node/npm (frontend).

set dotenv-load := true

backend := "backend"
frontend := "frontend"

# Show all available recipes.
default:
    @just --list

# --- Setup ------------------------------------------------------------------

# Install backend + frontend dependencies.
setup: setup-backend setup-frontend

# Install backend dependencies (creates .venv via uv).
# `dev` = test/lint; `etl` = GeoPandas/Typer CLI used by `just data-load`.
setup-backend:
    cd {{backend}} && uv sync --extra dev --extra etl

# Install frontend dependencies.
setup-frontend:
    cd {{frontend}} && npm install

# --- Database ---------------------------------------------------------------

# Start Postgres/PostGIS (detached) and wait for it to report healthy.
db-up:
    docker compose up -d --wait
    @echo "Database is healthy."

# Stop the database container (data volume is preserved).
db-down:
    docker compose down

# Stop the database AND delete its data volume (destructive).
db-reset:
    docker compose down -v

# Open a psql shell inside the database container.
db-shell:
    docker exec -it praxis-db psql -U ${POSTGRES_USER:-praxis} -d ${POSTGRES_DB:-praxis}

# --- Migrations -------------------------------------------------------------

# Apply all pending migrations.
migrate:
    cd {{backend}} && uv run alembic upgrade head

# Roll back one migration (used to verify 0002 downgrades cleanly).
migrate-down:
    cd {{backend}} && uv run alembic downgrade -1

# Create a new autogenerated migration: `just makemigration "add incidents"`.
makemigration message:
    cd {{backend}} && uv run alembic revision --autogenerate -m "{{message}}"

# --- Run --------------------------------------------------------------------

# Run the FastAPI backend (uvicorn, auto-reload).
api:
    cd {{backend}} && uv run uvicorn app.main:app --reload --port 8000

# Run the Vite frontend dev server.
web:
    cd {{frontend}} && npm run dev

# Run backend + frontend together (Ctrl-C stops both).
dev:
    just api & just web & wait

# --- Data -------------------------------------------------------------------

# Full seed-scenario pipeline: admin, flood extent, OSM, discharge, weather, incidents.
data-load *args:
    cd {{backend}} && uv run python -m app.cli seed-scenario {{args}}

# Honesty dashboard: row counts per table with source and real/synthetic status.
data-report:
    cd {{backend}} && uv run python -m app.cli data-report

# Reproducible demo: (re)create the two showcase playbooks + fixed-seed stress
# runs so the robustness reversal and inverted-alignment insight always appear.
# Idempotent; requires `just data-load` to have run first.
demo-seed:
    cd {{backend}} && uv run python -m app.cli demo-seed

# --- Quality ----------------------------------------------------------------

# Run backend + frontend test suites.
test: test-backend test-frontend

test-backend:
    cd {{backend}} && uv run pytest -m "not integration"

# PostGIS integration tests (requires `just db-up && just migrate`; seed tests need `just data-load`).
test-integration:
    cd {{backend}} && uv run pytest -o addopts="-ra -q" -m integration

test-frontend:
    cd {{frontend}} && npm run test

# Lint everything (Ruff + Biome + tsc).
lint:
    cd {{backend}} && uv run ruff check .
    cd {{frontend}} && npm run lint
    cd {{frontend}} && npm run typecheck

# Auto-format everything (Ruff + Biome).
format:
    cd {{backend}} && uv run ruff format .
    cd {{backend}} && uv run ruff check --fix .
    cd {{frontend}} && npm run format

# Build the production frontend bundle.
build:
    cd {{frontend}} && npm run build

# --- Production (Docker) -----------------------------------------------------

# A distinct project name keeps the prod stack isolated from the dev database.
prod_compose := "docker compose -p praxis-prod -f docker-compose.prod.yml --env-file .env.prod"

# Build the production images (api + web).
prod-build:
    {{prod_compose}} build

# Bring up the full production stack (db + api + web) in the background.
# The API applies migrations on start; open http://localhost:${WEB_PORT:-8080}.
prod-up:
    {{prod_compose}} up -d --build

# Tail logs from the production stack.
prod-logs:
    {{prod_compose}} logs -f

# Stop the production stack (data volume preserved).
prod-down:
    {{prod_compose}} down

# Load the seed scenario INTO the production database (real public data; needs
# network + the ETL extra). Runs the CLI in a throwaway api container.
prod-data-load:
    {{prod_compose}} run --rm --entrypoint "" api sh -c "uv sync --frozen --extra etl && uv run python -m app.cli seed-scenario"

# Create the showcase playbooks in the production database (idempotent).
prod-demo-seed:
    {{prod_compose}} run --rm --entrypoint "" api python -m app.cli demo-seed
