# Praxis — developer command runner.
# Usage: `just <recipe>`. Run `just` with no arguments to list recipes.
# Requires: docker, uv (backend), node/npm (frontend).

set dotenv-load := true

backend := "backend"
frontend := "frontend"

# Show all available recipes.
default:
    @just --list

# --- Setup ------------------------------------------------------------------

# Install backend + frontend dependencies.
setup: setup-backend setup-frontend

# Install backend dependencies (creates .venv via uv).
setup-backend:
    cd {{backend}} && uv sync --extra dev

# Install frontend dependencies.
setup-frontend:
    cd {{frontend}} && npm install

# --- Database ---------------------------------------------------------------

# Start Postgres/PostGIS (detached) and wait for it to report healthy.
db-up:
    docker compose up -d --wait
    @echo "Database is healthy."

# Stop the database container (data volume is preserved).
db-down:
    docker compose down

# Stop the database AND delete its data volume (destructive).
db-reset:
    docker compose down -v

# Open a psql shell inside the database container.
db-shell:
    docker exec -it praxis-db psql -U ${POSTGRES_USER:-praxis} -d ${POSTGRES_DB:-praxis}

# --- Migrations -------------------------------------------------------------

# Apply all pending migrations.
migrate:
    cd {{backend}} && uv run alembic upgrade head

# Create a new autogenerated migration: `just makemigration "add incidents"`.
makemigration message:
    cd {{backend}} && uv run alembic revision --autogenerate -m "{{message}}"

# --- Run --------------------------------------------------------------------

# Run the FastAPI backend (uvicorn, auto-reload).
api:
    cd {{backend}} && uv run uvicorn app.main:app --reload --port 8000

# Run the Vite frontend dev server.
web:
    cd {{frontend}} && npm run dev

# Run backend + frontend together (Ctrl-C stops both).
dev:
    just api & just web & wait

# --- Quality ----------------------------------------------------------------

# Run backend + frontend test suites.
test: test-backend test-frontend

test-backend:
    cd {{backend}} && uv run pytest

test-frontend:
    cd {{frontend}} && npm run test

# Lint everything (Ruff + Biome + tsc).
lint:
    cd {{backend}} && uv run ruff check .
    cd {{frontend}} && npm run lint
    cd {{frontend}} && npm run typecheck

# Auto-format everything (Ruff + Biome).
format:
    cd {{backend}} && uv run ruff format .
    cd {{backend}} && uv run ruff check --fix .
    cd {{frontend}} && npm run format

# Build the production frontend bundle.
build:
    cd {{frontend}} && npm run build
