import type { Brief } from "@/lib/api";

/** A representative template-generated brief for component tests. */
export const TEMPLATE_BRIEF: Brief = {
  id: 1,
  scenario_slug: "2017-sw-monsoon-kalu-ganga",
  playbook_id: 2,
  stress_run_id: 5,
  generator: "template",
  model: null,
  created_at: "2026-09-18T09:00:00Z",
  facts: {
    version: 1,
    scenario: {
      slug: "2017-sw-monsoon-kalu-ganga",
      name: "2017 SW-Monsoon Floods",
      hazard_type: "flood",
      status: "historical",
      event_date: "2017-05-26",
      description: "Monsoon floods in the Kalu Ganga basin.",
    },
    strategy: {
      name: "Wide coverage",
      description: null,
      priority_regions: [
        {
          pcode: "LK11",
          name: "Colombo",
          population: 2459998,
          at_risk_population: 367562,
          is_access_impaired: true,
        },
      ],
      priority_region_count: 1,
      activated_shelter_count: 200,
      activated_capacity: 60000,
      capacity_known: 0,
      capacity_assumed: 60000,
      assumed_capacity_shelters: 200,
      response_teams: 260,
      boats: 0,
      team_capacity: 500,
      boat_capacity: 200,
      response_capacity: 130000,
      allocation: "proportional_to_need",
      evacuation_threshold: 50000,
      avoid_closed_roads: true,
      displacement_rate_pct: 15,
    },
    scorecard: {
      overall: 63.5,
      metrics: [
        {
          key: "population_coverage",
          label: "Population coverage",
          score: 70.0,
          weight_pct: 35,
          provenance: "real",
          raw: {},
          notes: [],
        },
        {
          key: "accessibility",
          label: "Accessibility",
          score: 25.0,
          weight_pct: 15,
          provenance: "synthetic",
          raw: {},
          notes: [],
        },
      ],
      total_at_risk: 657301,
      covered_at_risk: 367562,
      uncovered_at_risk: 289739,
      people_needing_shelter: 55134,
      coverage_gap_count: 3,
    },
    coverage_gaps: [{ pcode: "LK32", name: "Galle", at_risk_population: 108294 }],
    robustness: {
      point_overall: 63.5,
      median: 58.0,
      p05: 48.0,
      p25: 54.0,
      p75: 62.0,
      p95: 66.0,
      worst_plausible: 48.0,
      probability_meets_target_pct: 42,
      target_score: 60,
      n_iterations: 500,
      seed: 2024,
      uses_synthetic_data: true,
      epistemic_note: "Modeled (epistemic) uncertainty, not measured forecast spread.",
      point_is_optimistic: true,
    },
    assumptions: ["Displacement rate: 15% of at-risk population needs shelter."],
    synthetic_influences: ["Accessibility is computed from synthetic road-closure sample data."],
    uses_synthetic_data: true,
  },
  content: {
    version: 1,
    generator: "template",
    headline: "Operational brief — Wide coverage",
    sections: [
      {
        key: "situation",
        title: "Situation overview",
        paragraphs: ["An estimated 657,301 people are at risk."],
        from_template: true,
      },
      {
        key: "performance",
        title: "Expected performance",
        paragraphs: ["The strategy scores 63.5/100."],
        from_template: true,
      },
      {
        key: "provenance",
        title: "Assumptions & data provenance",
        paragraphs: ["Figures validated against source."],
        from_template: true,
      },
    ],
  },
  guard: { ok: true, sections: [], repaired_sections: [] },
};
