"""domain model

Revision ID: a322295f213c
Revises: 0001_postgis
Create Date: 2026-09-17 01:49:18.640864
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# Geometry columns and the tables that carry them; GIST indexes are created
# explicitly (the models declare spatial_index=False so the DDL lives here).
_GEOM_COLUMNS: list[tuple[str, str]] = [
    ("admin_region", "geom"),
    ("scenario", "center"),
    ("hazard_layer", "geom"),
    ("incident", "geom"),
    ("river_point", "geom"),
    ("road_segment", "geom"),
    ("shelter", "geom"),
    ("weather_reading", "geom"),
]


# revision identifiers, used by Alembic.
revision: str = "0002_domain_model"
down_revision: str | None = "0001_postgis"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source")),
        sa.UniqueConstraint("key", name=op.f("uq_data_source_key")),
    )
    op.create_table(
        "admin_region",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("pcode", sa.String(length=20), nullable=False),
        sa.Column("parent_pcode", sa.String(length=20), nullable=True),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("name_si", sa.String(length=255), nullable=True),
        sa.Column("name_ta", sa.String(length=255), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_pcode"],
            ["admin_region.pcode"],
            name=op.f("fk_admin_region_parent_pcode_admin_region"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_admin_region_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_region")),
        # Unique constraint (not just an index) so the self-referential
        # parent_pcode FK can reference pcode within this CREATE TABLE.
        sa.UniqueConstraint("pcode", name="uq_admin_region_pcode"),
    )
    op.create_index(op.f("ix_admin_region_level"), "admin_region", ["level"], unique=False)
    op.create_index(
        op.f("ix_admin_region_parent_pcode"), "admin_region", ["parent_pcode"], unique=False
    )
    op.create_table(
        "river_point",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("river_name", sa.String(length=255), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_river_point_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_river_point")),
    )
    op.create_index(op.f("ix_river_point_key"), "river_point", ["key"], unique=True)
    op.create_table(
        "road_segment",
        sa.Column("osm_id", sa.String(length=40), nullable=False),
        sa.Column("road_class", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_road_segment_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_road_segment")),
    )
    op.create_index(op.f("ix_road_segment_osm_id"), "road_segment", ["osm_id"], unique=True)
    op.create_table(
        "scenario",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "hazard_type",
            sa.Enum(
                "flood",
                "landslide",
                "cyclone",
                "multi",
                name="hazard_type",
                native_enum=False,
                length=20,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "historical",
                "simulated",
                "live",
                name="scenario_status",
                native_enum=False,
                length=20,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("bbox_min_lon", sa.Float(), nullable=True),
        sa.Column("bbox_min_lat", sa.Float(), nullable=True),
        sa.Column("bbox_max_lon", sa.Float(), nullable=True),
        sa.Column("bbox_max_lat", sa.Float(), nullable=True),
        sa.Column(
            "center",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_scenario_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario")),
    )
    op.create_index(op.f("ix_scenario_slug"), "scenario", ["slug"], unique=True)
    op.create_table(
        "discharge_forecast",
        sa.Column("river_point_id", sa.Integer(), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_date", sa.Date(), nullable=False),
        sa.Column("discharge_mean", sa.Float(), nullable=True),
        sa.Column("discharge_median", sa.Float(), nullable=True),
        sa.Column("discharge_p25", sa.Float(), nullable=True),
        sa.Column("discharge_p75", sa.Float(), nullable=True),
        sa.Column("discharge_min", sa.Float(), nullable=True),
        sa.Column("discharge_max", sa.Float(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["river_point_id"],
            ["river_point.id"],
            name=op.f("fk_discharge_forecast_river_point_id_river_point"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
            name=op.f("fk_discharge_forecast_scenario_id_scenario"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_discharge_forecast_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discharge_forecast")),
        sa.UniqueConstraint(
            "river_point_id", "scenario_id", "valid_date", name="uq_discharge_point_scenario_date"
        ),
    )
    op.create_index(
        op.f("ix_discharge_forecast_river_point_id"),
        "discharge_forecast",
        ["river_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_forecast_scenario_id"),
        "discharge_forecast",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "hazard_layer",
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column(
            "layer_type",
            sa.Enum(
                "flood_extent",
                "landslide_susceptibility",
                "cyclone_track",
                "storm_surge",
                name="layer_type",
                native_enum=False,
                length=32,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("severity_class", sa.Integer(), nullable=True),
        sa.Column("severity_label", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
            name=op.f("fk_hazard_layer_scenario_id_scenario"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_hazard_layer_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hazard_layer")),
    )
    op.create_index(
        op.f("ix_hazard_layer_scenario_id"), "hazard_layer", ["scenario_id"], unique=False
    )
    op.create_table(
        "incident",
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_region_id", sa.Integer(), nullable=True),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_region_id"],
            ["admin_region.id"],
            name=op.f("fk_incident_admin_region_id_admin_region"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
            name=op.f("fk_incident_scenario_id_scenario"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_incident_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident")),
    )
    op.create_index(
        op.f("ix_incident_admin_region_id"), "incident", ["admin_region_id"], unique=False
    )
    op.create_index(op.f("ix_incident_external_id"), "incident", ["external_id"], unique=False)
    op.create_index(op.f("ix_incident_scenario_id"), "incident", ["scenario_id"], unique=False)
    op.create_table(
        "road_closure",
        sa.Column("road_segment_id", sa.Integer(), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["road_segment_id"],
            ["road_segment.id"],
            name=op.f("fk_road_closure_road_segment_id_road_segment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
            name=op.f("fk_road_closure_scenario_id_scenario"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_road_closure_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_road_closure")),
        sa.UniqueConstraint(
            "road_segment_id", "scenario_id", name="uq_road_closure_segment_scenario"
        ),
    )
    op.create_index(
        op.f("ix_road_closure_road_segment_id"), "road_closure", ["road_segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_road_closure_scenario_id"), "road_closure", ["scenario_id"], unique=False
    )
    op.create_table(
        "shelter",
        sa.Column("osm_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("admin_region_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_region_id"],
            ["admin_region.id"],
            name=op.f("fk_shelter_admin_region_id_admin_region"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_shelter_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shelter")),
    )
    op.create_index(
        op.f("ix_shelter_admin_region_id"), "shelter", ["admin_region_id"], unique=False
    )
    op.create_index(op.f("ix_shelter_osm_id"), "shelter", ["osm_id"], unique=True)
    op.create_table(
        "weather_reading",
        sa.Column("location_key", sa.String(length=80), nullable=False),
        sa.Column("valid_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("admin_region_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_region_id"],
            ["admin_region.id"],
            name=op.f("fk_weather_reading_admin_region_id_admin_region"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
            name=op.f("fk_weather_reading_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_reading")),
        sa.UniqueConstraint("location_key", "valid_time", name="uq_weather_location_time"),
    )
    op.create_index(
        op.f("ix_weather_reading_admin_region_id"),
        "weather_reading",
        ["admin_region_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_reading_location_key"), "weather_reading", ["location_key"], unique=False
    )
    # ### end Alembic commands ###

    # GIST spatial indexes on every geometry column.
    for table, column in _GEOM_COLUMNS:
        op.create_index(
            f"ix_{table}_{column}_gist",
            table,
            [column],
            unique=False,
            postgresql_using="gist",
        )


def downgrade() -> None:
    # Drop GIST spatial indexes first.
    for table, column in _GEOM_COLUMNS:
        op.drop_index(f"ix_{table}_{column}_gist", table_name=table)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_reading_location_key"), table_name="weather_reading")
    op.drop_index(op.f("ix_weather_reading_admin_region_id"), table_name="weather_reading")
    op.drop_table("weather_reading")
    op.drop_index(op.f("ix_shelter_osm_id"), table_name="shelter")
    op.drop_index(op.f("ix_shelter_admin_region_id"), table_name="shelter")
    op.drop_table("shelter")
    op.drop_index(op.f("ix_road_closure_scenario_id"), table_name="road_closure")
    op.drop_index(op.f("ix_road_closure_road_segment_id"), table_name="road_closure")
    op.drop_table("road_closure")
    op.drop_index(op.f("ix_incident_scenario_id"), table_name="incident")
    op.drop_index(op.f("ix_incident_external_id"), table_name="incident")
    op.drop_index(op.f("ix_incident_admin_region_id"), table_name="incident")
    op.drop_table("incident")
    op.drop_index(op.f("ix_hazard_layer_scenario_id"), table_name="hazard_layer")
    op.drop_table("hazard_layer")
    op.drop_index(op.f("ix_discharge_forecast_scenario_id"), table_name="discharge_forecast")
    op.drop_index(op.f("ix_discharge_forecast_river_point_id"), table_name="discharge_forecast")
    op.drop_table("discharge_forecast")
    op.drop_index(op.f("ix_scenario_slug"), table_name="scenario")
    op.drop_table("scenario")
    op.drop_index(op.f("ix_road_segment_osm_id"), table_name="road_segment")
    op.drop_table("road_segment")
    op.drop_index(op.f("ix_river_point_key"), table_name="river_point")
    op.drop_table("river_point")
    op.drop_index(op.f("ix_admin_region_parent_pcode"), table_name="admin_region")
    op.drop_index(op.f("ix_admin_region_level"), table_name="admin_region", if_exists=True)
    op.drop_table("admin_region")  # drops uq_admin_region_pcode with the table
    op.drop_table("data_source")
    # ### end Alembic commands ###
